Enhance VirtualNode Integration test suite
aws/aws-app-mesh-controller-for-k8s pull request #431
Opened 2021-01-28 07:59 UTC by achevuru

*Issue #, if available:*
NA
*Description of changes:*

 - Add mTLS based tests to the VirtualNode integration test suite.
 - PR also addresses an intermittent issue with VirtualNode - CloudMap Test.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-01-28 18:08 UTC, fawadkhaliq approved these changes

2021-01-28 18:09 UTC, fawadkhaliq requested changes
The cloud map virtual node test is still failing

```
Virtual Node scenarios
  /home/ssm-user/actions-runner/_work/aws-app-mesh-controller-for-k8s/aws-app-mesh-controller-for-k8s/test/integration/virtualnode/virtualnode_test.go:62
    should create a virtual node with CloudMap ServiceDiscovery enabled [It]
    /home/ssm-user/actions-runner/_work/aws-app-mesh-controller-for-k8s/aws-app-mesh-controller-for-k8s/test/integration/virtualnode/virtualnode_test.go:163

    Unexpected error:
        <*errors.errorString | 0xc000c043e0>: {
            s: "instance count mismatch",
        }
        instance count mismatch
    occurred
```

2021-01-28 23:54 UTC, achevuru commented
> The cloud map virtual node test is still failing
> 
> ```
> Virtual Node scenarios
>   /home/ssm-user/actions-runner/_work/aws-app-mesh-controller-for-k8s/aws-app-mesh-controller-for-k8s/test/integration/virtualnode/virtualnode_test.go:62
>     should create a virtual node with CloudMap ServiceDiscovery enabled [It]
>     /home/ssm-user/actions-runner/_work/aws-app-mesh-controller-for-k8s/aws-app-mesh-controller-for-k8s/test/integration/virtualnode/virtualnode_test.go:163
> 
>     Unexpected error:
>         <*errors.errorString | 0xc000c043e0>: {
>             s: "instance count mismatch",
>         }
>         instance count mismatch
>     occurred
> ```

It is due to Envoy pointing to Prod while the appmesh resources are created in Preview. Issue will resolve itself once we point the controller away from preview.

2021-01-29 19:28 UTC, fawadkhaliq approved these changes

2021-01-29 19:28 UTC, fawadkhaliq commented
> > The cloud map virtual node test is still failing
> > ```
> > Virtual Node scenarios
> >   /home/ssm-user/actions-runner/_work/aws-app-mesh-controller-for-k8s/aws-app-mesh-controller-for-k8s/test/integration/virtualnode/virtualnode_test.go:62
> >     should create a virtual node with CloudMap ServiceDiscovery enabled [It]
> >     /home/ssm-user/actions-runner/_work/aws-app-mesh-controller-for-k8s/aws-app-mesh-controller-for-k8s/test/integration/virtualnode/virtualnode_test.go:163
> > 
> >     Unexpected error:
> >         <*errors.errorString | 0xc000c043e0>: {
> >             s: "instance count mismatch",
> >         }
> >         instance count mismatch
> >     occurred
> > ```
> 
> It is due to Envoy pointing to Prod while the appmesh resources are created in Preview. Issue will resolve itself once we point the controller away from preview.

Preview set here: https://github.com/aws/aws-app-mesh-controller-for-k8s/pull/432 so we should be good once that is merged

2021-01-29 20:28 UTC, merged